baseURL = 'https://dheer.me'
languageCode = 'nl-be'
title = "Sofie D'heer"

## Menu Items
[menu]
  [[menu.main]]
  name = "Over"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Projecten"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#contact"
  weight = 3
