backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'Index'
    label: 'Index'
    folder: 'content'
    file: '_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Adres', name: 'address', widget: 'string' }

  - name: 'About'
    label: 'About'
    folder: 'content/about'
    file: 'description.md'
    editor:
      preview: true
    fields:
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Handgemaakte Kaartjes'
    name: 'cards'
    file: 'content/cards/_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
      - label: 'Kaartjes'
        name: 'cards'
        widget: 'list'
        collapsed: false
        fields:
          - { label: 'Titel', name: 'title', widget: 'string' }
          - { label: 'Sfeerbeeld', media_folder: /assets/images/cards, name: 'image', widget: 'image', choose_url: true}
